[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
# https://github.com/redhat-developer/yaml-language-server#language-server-settings
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://json.schemastore.org/circleciconfig.json" = ".circleci/config.yml"
#"values.schema.json" = "values.yaml" -> helm charts must add an inline $schema=./values.schema.json instead


[language-server.rust-analyzer.config.check]
command = "clippy"
